# Generated by Django 3.2.3 on 2023-08-09 10:30

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_follow_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='not_self_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('follower', django.db.models.expressions.F('author')), _negated=True), name='not_self_follow'),
        ),
    ]
