# Generated by Django 3.2.3 on 2023-08-23 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230822_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Время приготовления должнобыть больше или равно 1 минуте.'), django.core.validators.MaxValueValidator(limit_value=480, message='Время приготовления должнобыть меньше 8 часов.')], verbose_name='Время приготовления'),
        ),
    ]
